### ISSUE TITLE
[Suggestion] Don't run the command while any text is selected on the page

### ISSUE THREAD

**Issue by lukaszpolowczyk** [metonym/svelte-keydown#1]
I have a suggestion for improvement.

The `blockIfAnyTextboxSelected` attribute - if `true`, it does not run the command as long as any text box is selected on the page (`input[type=text]`, `[contexteditable=true]`, `textarea`).
```svelte
<Keydown blockIfAnyTextboxSelected={true} on:key={ ({detail})=> detail==="w"&& fun() } />
```
The point is that the command should not be invoked when typing in a text field.

But input `input[type=number]` would not be taken into account by `blockIfAnyTextboxSelected` - or block it in a separate way, maybe with a separate attribute...
Without it, you have to prepare a complex checking function and add it to the command.

---

Another improvement would be to make a 'detail' attribute which causes the command to only run if detail matches:
```svelte
<Keydown detail="w" on:key={()=> fun() } />
```
or
```svelte
<Keydown details={["w","s"]} on:key={()=> fun() } />
```

...thanks to this, the function itself can be simplified - as you can see.

You can think of better names for `blockIfAnyTextboxSelected` and `detail`/`details`. :)

What do you think?

**Comment by metonym** [comment]
@lukaszpolowczyk I think that's a great suggestion.

I've added a `pauseOnInput` prop which will not capture input events if set to `true`.

See the example in the documentation: https://metonym.github.io/svelte-keydown/#pause-on-input

Published to NPM in [v0.3.0](https://github.com/metonym/svelte-keydown/releases/tag/v0.3.0)
